version: '3'
services:
    server:
        build: 
            context: .
            dockerfile: ./proxy/Dockerfile
        container_name: proxy_server
        ports: 
            - "8080:8080"
        tty: true
        depends_on: 
            - db
            - redis
    db:
        image: postgres
        container_name: 'auth_server_db'
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports: 
            - 5432
        restart: "always"
        tty: true
        volumes: 
            - auth_server_db_volume:/var/lib/postgresql/data
    redis:
        image: redis
        ports: 
            - 6379
        volumes:
            - auth_redis_volume:/data
        tty: true
    app:
        build:
            context: .
            dockerfile: ./app/Dockerfile
        container_name: auth_server
        ports: 
            - 9001
        depends_on:
            - db
            - redis
    
volumes: 
    auth_server_db_volume:
        driver: "local"
    auth_redis_volume:
        driver: "local"
