version: '3'
services:
    server:
        build: 
            context: .
            dockerfile: ./proxy/Dockerfile
        container_name: proxy_server
        ports: 
            - "8080:8080"
        tty: true
        depends_on: 
            - db
    db:
        image: postgres
        container_name: 'auth_server_db'
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports: 
            - 5432
        restart: "always"
        tty: true
        volumes: 
            - auth_server_db_volume:/var/lib/postgresql/data
    app:
        build:
            context: .
            dockerfile: ./app/Dockerfile
        container_name: auth_server
        ports: 
            - 9001
        depends_on:
            - db
    
volumes: 
    auth_server_db_volume:
        driver: "local"
