version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile.develop
    volumes:
      - ./app/:/go/app/src/
    ports:
      - 9001:9001
    tty: true
    depends_on:
      - db
      - redis
  frontend:
    build:
        context: .
        dockerfile: ./frontend/Dockerfile.develop
    ports:
        - 3000:3000
    volumes: 
        - ./frontend/:/frontend/src/
    tty: true
  db:
    image: postgres
    ports:
        - "5432:5432"
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=secret
    volumes:
        - auth_server_develop_volume:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
        - 6379:6379
    volumes: 
        - auth_server_develop_redis_volume:/data/
    restart: always 
volumes: 
    auth_server_develop_volume:
        driver: local
    auth_server_develop_redis_volume:
        driver: local
