version: '3'
services: 
    db:
        image: postgres
        container_name: 'auth_server_testdb'
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports: 
            - 15434:5432
        restart: "always"
        tty: true
        volumes: 
            - auth_server_testdb_volume:/var/lib/postgresql/data
    redis:
        image: redis
        tty: true
        ports:
            - 6390:6379
        volumes: 
            - auth_server_redis_volume:/data
            - ./init_redis/:/docker-entrypoint.sh
volumes: 
    auth_server_testdb_volume:
        driver: "local"
    auth_server_redis_volume:
        driver: "local"
