version: '3'
services: 
    db:
        image: postgres
        container_name: 'auth_server_testdb'
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports: 
            - 15433:5432
        restart: "always"
        tty: true
        volumes: 
            - auth_server_testdb_volume:/var/lib/postgresql/data
volumes: 
    auth_server_testdb_volume:
        driver: "local"
